[command]
default=conda run -n ugants-dev ugants run rose-app-run.conf

[ugants]
app=ugants.apps.generate_mask

[ugants.outputs]
result=${ROSE_DATA}/${ROSE_TASK_NAME}.nc

[ugants.settings]
mask_type=${CYLC_TASK_PARAM_mask_type}

[ugants.sources]
land_fraction=${TEST_SOURCES_DIR}/global/C48/land_fraction.nc
