# (C) Crown Copyright, Met Office. All rights reserved.
#
# This file is part of UG-ANTS and is released under the BSD 3-Clause license.
# See LICENSE.txt in the root of the repository for full licensing details.
import numpy as np
import pytest
from iris.experimental.ugrid import Mesh
from slam import Transform
from ugants.utils.cube import mesh2cube
from ugants.utils.mesh_generator.panel import PanelBuilder


@pytest.mark.parametrize("c", [4, 8, 16])
@pytest.mark.parametrize("panel_id", range(6))
def test_slammed_coordinates(c, panel_id):
    """Test that a cube generated by the panel mesh can be slammed appropriately.

    In generating the mesh, the face lat-lon coordinates are created and stored
    as attributes on the PanelBuilder. These should be identical to the coordinates
    that geovista slam generates (in practice there will be floating point differences).
    """
    panel_builder = PanelBuilder(c, panel_id)
    ugrid_cube = mesh2cube(panel_builder.to_iris_mesh())
    slam_cube = Transform.from_ugrid(ugrid_cube)

    expected_lon_coord_array = panel_builder.face_lons
    expected_lat_coord_array = panel_builder.face_lats

    actual_lon_coord_array = slam_cube.coord("longitude").points
    actual_lat_coord_array = slam_cube.coord("latitude").points

    np.testing.assert_array_almost_equal(
        actual_lon_coord_array, expected_lon_coord_array
    )
    np.testing.assert_array_almost_equal(
        actual_lat_coord_array, expected_lat_coord_array
    )


def test_invalid_panel_id_exception():
    expected_msg = r"panel_id should be in range \[0, 5\], got unexpected value 6"
    with pytest.raises(ValueError, match=expected_msg):
        PanelBuilder(4, 6)


class TestToIrisMesh:
    """Tests for the to_iris_mesh method."""

    @pytest.mark.parametrize("c", [4, 8, 16])
    @pytest.mark.parametrize("panel_id", range(6))
    def test_mesh_type(self, c, panel_id):
        """A intentionally simple test to check mesh generation."""
        mesh = PanelBuilder(c, panel_id).to_iris_mesh()
        assert isinstance(mesh, Mesh)
