mode=rose_bunch

[bunch]
command-format=ug-ants-launch nccmp --var-diff-count 5 --global --data --force \
              =--metadata --nans-are-equal --buffer-entire-var --statistics \
              =--globalex=_NCProperties,Conventions,suite_provenance \
              =--Attribute=history,suite_provenance  $source_dir/%(filelist)s \
              =$target_dir/%(filelist)s
pool-size=12
names=$filelist

[bunch-args]
filelist=$filelist

[env]
source_dir=${ROSE_DATA}
target_dir=${TEST_RESULTS_DIR}
